-- Research corpus schema for Oracle Autonomous Database 23ai / 26ai.
-- Run as the CORPUS user via Database Actions → SQL.
--
-- Idempotent: safe to re-run; will skip objects that already exist.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) Artifacts table — one row per blob (generated by NotebookLM or uploaded).
--    Object Storage holds the bytes; this table is the searchable catalog.
-- ─────────────────────────────────────────────────────────────────────────────
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE artifacts (
      id                      VARCHAR2(26)  NOT NULL,            -- ULID (26 chars, sortable, URL-safe)
      kind                    VARCHAR2(32)  NOT NULL,            -- audio|report|video|quiz|flashcards|infographic|slides|data_table|upload
      origin                  VARCHAR2(16)  NOT NULL,            -- notebooklm | upload
      title                   VARCHAR2(512) NOT NULL,
      notebook_id             VARCHAR2(64),                      -- nullable for uploads
      artifact_id             VARCHAR2(64),                      -- source artifact id from NotebookLM (nullable)
      bucket                  VARCHAR2(128) NOT NULL,
      object_name             VARCHAR2(1024) NOT NULL,
      mime_type               VARCHAR2(128),
      size_bytes              NUMBER,
      tags                    JSON,                              -- ['q2-earnings','tencent']
      metadata                JSON,                              -- arbitrary kind-specific extras (e.g. format/length)
      -- M7 transcription tracking (nullable for pre-M7 rows + non-audio/video kinds)
      transcription_status    VARCHAR2(20),                      -- null|pending|transcribing|done|failed|skipped
      transcription_job_ocid  VARCHAR2(255),                     -- OCI Speech job OCID for polling
      transcribed_at          TIMESTAMP WITH LOCAL TIME ZONE,
      transcription_error     VARCHAR2(2000),
      created_at              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_artifacts PRIMARY KEY (id),
      CONSTRAINT ck_artifacts_origin CHECK (origin IN ('notebooklm','upload'))
    )
  ]';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
/

-- Useful filter indexes (idempotent via PL/SQL block).
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
  PRAGMA EXCEPTION_INIT(e_already_exists, -1408);
BEGIN
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_artifacts_kind        ON artifacts(kind)';        EXCEPTION WHEN e_already_exists THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_artifacts_origin      ON artifacts(origin)';      EXCEPTION WHEN e_already_exists THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_artifacts_notebook    ON artifacts(notebook_id)'; EXCEPTION WHEN e_already_exists THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_artifacts_created_at  ON artifacts(created_at DESC)'; EXCEPTION WHEN e_already_exists THEN NULL; END;
  -- M7: hot-path index for the transcription poller (small, cheap).
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_artifacts_trx_status  ON artifacts(transcription_status)'; EXCEPTION WHEN e_already_exists THEN NULL; END;
END;
/

-- ─────────────────────────────────────────────────────────────────────────────
-- 1b) Dedup: partial-like unique index on (notebook_id, artifact_id).
--
--     We only want NotebookLM artifacts to be unique per (notebook, artifact)
--     pair; uploads (both columns NULL) must be free to repeat. Oracle has
--     no partial-index syntax, so we fake it with function-based columns
--     that evaluate to NULL unless BOTH source columns are non-NULL. A row
--     where any key column is NULL is not indexed (Oracle's standard rule
--     for function-based unique indexes), so uploads are untouched.
-- ─────────────────────────────────────────────────────────────────────────────
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
  PRAGMA EXCEPTION_INIT(e_already_exists, -1408);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE UNIQUE INDEX ix_artifacts_nb_aid_unique ON artifacts(
      CASE WHEN notebook_id IS NOT NULL AND artifact_id IS NOT NULL THEN notebook_id END,
      CASE WHEN notebook_id IS NOT NULL AND artifact_id IS NOT NULL THEN artifact_id END
    )
  ]';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
/

-- Oracle Text full-text index on title for cheap title search alongside vector search.
-- Wrapped in a block so re-runs don't fail.
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -29855);  -- index already exists
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEARCH INDEX ix_artifacts_title_fts ON artifacts(title) FOR TEXT';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
/

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) Artifact chunks — one row per text chunk, with VECTOR embedding.
--    3072-dim FLOAT32 (Gemini gemini-embedding-2), cosine distance.
-- ─────────────────────────────────────────────────────────────────────────────
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE artifact_chunks (
      id              VARCHAR2(26)  NOT NULL,
      artifact_id     VARCHAR2(26)  NOT NULL,
      ordinal         NUMBER        NOT NULL,
      text            CLOB          NOT NULL,
      char_start      NUMBER,
      char_end        NUMBER,
      token_count     NUMBER,
      -- Gemini gemini-embedding-2 is 3072 dimensions.
      embedding       VECTOR(3072, FLOAT32) NOT NULL,
      created_at      TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_artifact_chunks PRIMARY KEY (id),
      CONSTRAINT fk_artifact_chunks_artifact FOREIGN KEY (artifact_id)
        REFERENCES artifacts(id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
/

DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
  PRAGMA EXCEPTION_INIT(e_already_exists, -1408);
BEGIN
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_chunks_artifact ON artifact_chunks(artifact_id, ordinal)'; EXCEPTION WHEN e_already_exists THEN NULL; END;
END;
/

-- Approximate vector index (HNSW-style, in-memory) for fast kNN.
-- ORGANIZATION INMEMORY NEIGHBOR GRAPH is the 23ai/26ai HNSW variant.
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
  PRAGMA EXCEPTION_INIT(e_already_exists, -51000);  -- vector index errors
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE VECTOR INDEX ix_chunks_vec
      ON artifact_chunks(embedding)
      ORGANIZATION INMEMORY NEIGHBOR GRAPH
      DISTANCE COSINE
      WITH TARGET ACCURACY 90
  ]';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
/

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) Verification — should print 2 tables + several indexes.
-- ─────────────────────────────────────────────────────────────────────────────
SELECT table_name FROM user_tables WHERE table_name IN ('ARTIFACTS','ARTIFACT_CHUNKS') ORDER BY 1;
SELECT index_name, table_name FROM user_indexes WHERE table_name IN ('ARTIFACTS','ARTIFACT_CHUNKS') ORDER BY 2,1;
